requirements: Revert to earlier redis,django-redis libs
Upgrading to the most recent versions of these resulted in strange
intermittent errors in redis/_compat.py line 81:
    AttributeError: 'str' object has no attribute 'iteritems'